/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function compileForNode(source: string, filename: string): string
export declare function compileForNodeJson(source: string, filename: string): string
export declare function compileRx(source: string, filename: string): string
